[package]
name = "actix-jwt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
chrono = "0.4.35"
jsonwebtoken = "9.2.0"
serde = { version = "1.0.197", features = ["derive"] }
